package com.vimond.StorageArchitecture.Jobs;

public enum JobName
{
	SIMPLE_TOP_COUNTRIES, SIMPLE_TOP_ASSETS, SIMPLE_CONTENT_LOCATION, SIMPLE_TOP_APP, SIMPLE_DATA_LOADER, COUNTER_EVENT_TYPE, COUNTER_END_BY_ASSET, START_EVENTS, COUNTER_START_BY_ASSET, TOP_BROWSER, TOP_OS, TOP_VIDEOFORMAT
}
