package com.vimond.utils.data;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Entity class for the event handled by the Real Time layer. It has some differences with the Spark one according to the fields used
 * @author matteoremoluzzi
 *
 */
public class StormEvent extends Event implements Serializable
{
	private static final long serialVersionUID = 1733723878642302297L;
	
	@JsonProperty("data.ip")
	public String getIpAddress()
	{
		return super.getIpAddress();
	}

	@JsonIgnore
	public String getCountryName()
	{
		return super.getCountryName();
	}
	
	@JsonProperty("data.appName")
	public String getAppName()
	{
		return super.getAppName();
	}
	
	@JsonProperty("data.assetId")
	public Integer getAssetId()
	{
		return super.getAssetId();
	}
	
	@JsonProperty("data.assetName")
	public String getAssetName()
	{
		return super.getAssetName();
	}
	
	@JsonIgnore
	public String getUserAgent()
	{
		return super.getUserAgent();
	}
	
	@JsonProperty("data.videoFormat")
	public String getVideoFormat()
	{
		return super.getVideoFormat();
	}
	
	@JsonProperty("data.playerEvent")
	public String getPlayerEvent()
	{
		return super.getPlayerEvent();
	}
	
	/**
	 * 
	 * Fields generated by useragent augmentation or for aggregation purposes on elasticsearch
	 * 
	 */
	
	public void setCountryName(String countryName)
	{
		setGenericValue(Constants.COUNTRY_NAME, countryName);
	}

	public void setLatitude(Double latitude)
	{
		setGenericValue(Constants.LATITUDE, latitude);
	}

	public void setLongitude(Double longitude)
	{
		setGenericValue(Constants.LONGITUDE, longitude);
	}

	public void setCity(String city)
	{
		setGenericValue(Constants.CITY, city);
	}
	
	@JsonIgnore
	public void setBrowser(String browser)
	{
		setGenericValue(Constants.BROWSER, browser);
	}
	
	public void setCounter()
	{
		setGenericValue(Constants.COUNTER, 1);
	}

	@JsonIgnore
	public void setOs(String os)
	{
		setGenericValue(Constants.OS, os);
	}

}
