# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

########### These MUST be filled in for a storm configuration
storm.zookeeper.servers:
    - "172.31.24.41"
#     - "server2"
#
nimbus.host: "172.31.25.237"
nimbus.host.port: 6627

storm.local.dir: "/var/local/storm"
#
#
# ##### These may optionally be filled in:
#
## List of custom serializations
#topology.kryo.register:
#     - com.vimond.utils.data.StormEvent
#     - org.mycompany.MyType2: org.mycompany.MyType2Serializer
#
## List of custom kryo decorators
# topology.kryo.decorators:
#     - org.mycompany.MyDecorator
#
## Locations of the drpc servers
# drpc.servers:
#     - "server1"
#     - "server2"

es.index.auto.create: "true"
es.nodes: "172.31.23.179"
es.port: 9200
es.input.json: "true"
es.storm.bolt.flush.entries.size: 1500
es.batch.size.entries: 1500
es.batch.size.bytes: "30mb"
es.storm.bolt.tick.tuple.flush: "true"

topology.workers: 8
topology.debug: false
topology.acker.executors: 0
topology.message.timeout.secs: 30
topology.max.spout.pending: 10000
topology.fall.back.on.java.serialization: false

#only for master
ui.host: 52.19.142.246
nimbus.childopts: "-Xmx1024m"

#only for workers
supervisor.childopts: "-Xmx512m"
worker.childopts: "-Xmx2048m"

supervisor.slots.ports:
    - 6700
    - 6701
    - 6702
    - 6703
    - 6704

## Metrics Consumers
# topology.metrics.consumer.register:
#   - class: "backtype.storm.metric.LoggingMetricsConsumer"
#     parallelism.hint: 1
#   - class: "org.mycompany.MyMetricsConsumer"
#     parallelism.hint: 1
#     argument:
#       - endpoint: "metrics-collector.mycompany.org"


topology.executor.receive.buffer.size: 8192
topology.executor.send.buffer.size: 8192
